name: Test

on: [push, pull_request]


jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04 ]
        compiler: [ 'g++', 'clang++' ]
        include:
          - os: windows-2022
            compiler: ''
          - os: macos-11
            compiler: ''

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
            
      - name: Setup compiler
        if: ${{ matrix.compiler != '' }}
        run: echo "CXX=${{ matrix.compiler }}" >> $GITHUB_ENV

      - name: Test
        run: "set -e; cd test; mkdir build; cd build; cmake ..; cmake --build ."
        shell: bash
